# Generated by Django 2.1.5 on 2019-02-09 04:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user_profile', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('date_created', models.DateField(auto_now_add=True)),
                ('description', models.TextField()),
                ('status', models.CharField(default='active', max_length=10)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('designer', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='user_profile.Designer')),
            ],
        ),
        migrations.CreateModel(
            name='ContractFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(verbose_name='File Description')),
                ('file_path', models.FileField(upload_to='contract_files/', verbose_name='Attach file')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contract.Contract')),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(default=3)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='contract.Contract')),
                ('designer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_profile.Designer')),
            ],
        ),
    ]
